### ISSUE TITLE
AttributeError: 'FluxNetworkTrainer' object has no attribute 'num_train_epochs'

### ISSUE THREAD

**Issue by whmc76** [kijai/ComfyUI-FluxTrainer#10]
2024-08-24 23:30:57 INFO     got prompt                                                                  server.py:504
Namespace(console_log_level=None, console_log_file=None, console_log_simple=False, v2=False, v_parameterization=False, pretrained_model_name_or_path=None, tokenizer_cache_dir=None, train_data_dir=None, cache_info=False, shuffle_caption=False, caption_separator=',', caption_extension='.caption', caption_extention=None, keep_tokens=0, keep_tokens_separator='', secondary_separator=None, enable_wildcard=False, caption_prefix=None, caption_suffix=None, color_aug=False, flip_aug=False, face_crop_aug_range=None, random_crop=False, debug_dataset=False, resolution=None, cache_latents=False, vae_batch_size=1, cache_latents_to_disk=False, enable_bucket=False, min_bucket_reso=256, max_bucket_reso=1024, bucket_reso_steps=64, bucket_no_upscale=False, token_warmup_min=1, token_warmup_step=0, alpha_mask=False, dataset_class=None, caption_dropout_rate=0.0, caption_dropout_every_n_epochs=0, caption_tag_dropout_rate=0.0, reg_data_dir=None, in_json=None, dataset_repeats=1, output_dir=None, output_name=None, huggingface_repo_id=None, huggingface_repo_type=None, huggingface_path_in_repo=None, huggingface_token=None, huggingface_repo_visibility=None, save_state_to_huggingface=False, resume_from_huggingface=False, async_upload=False, save_precision=None, save_every_n_epochs=None, save_every_n_steps=None, save_n_epoch_ratio=None, save_last_n_epochs=None, save_last_n_epochs_state=None, save_last_n_steps=None, save_last_n_steps_state=None, save_state=False, save_state_on_train_end=False, resume=None, train_batch_size=1, max_token_length=None, mem_eff_attn=False, torch_compile=False, dynamo_backend='inductor', xformers=False, sdpa=False, vae=None, max_train_steps=1600, max_train_epochs=None, max_data_loader_n_workers=8, persistent_data_loader_workers=False, seed=None, gradient_checkpointing=False, gradient_accumulation_steps=1, mixed_precision='no', full_fp16=False, full_bf16=False, fp8_base=False, ddp_timeout=None, ddp_gradient_as_bucket_view=False, ddp_static_graph=False, clip_skip=None, logging_dir=None, log_with=None, log_prefix=None, log_tracker_name=None, wandb_run_name=None, log_tracker_config=None, wandb_api_key=None, log_config=False, noise_offset=None, noise_offset_random_strength=False, multires_noise_iterations=None, ip_noise_gamma=None, ip_noise_gamma_random_strength=False, multires_noise_discount=0.3, adaptive_noise_scale=None, zero_terminal_snr=False, min_timestep=None, max_timestep=None, loss_type='l2', huber_schedule='snr', huber_c=0.1, lowram=False, highvram=False, sample_every_n_steps=None, sample_at_first=False, sample_every_n_epochs=None, sample_prompts=None, sample_sampler='ddim', config_file=None, output_config=False, metadata_title=None, metadata_author=None, metadata_description=None, metadata_license=None, metadata_tags=None, prior_loss_weight=1.0, conditioning_data_dir=None, masked_loss=False, deepspeed=False, zero_stage=2, offload_optimizer_device=None, offload_optimizer_nvme_path=None, offload_param_device=None, offload_param_nvme_path=None, zero3_init_flag=False, zero3_save_16bit_model=False, fp16_master_weights_and_gradients=False, optimizer_type='', use_8bit_adam=False, use_lion_optimizer=False, learning_rate=2e-06, max_grad_norm=1.0, optimizer_args=None, lr_scheduler_type='', lr_scheduler_args=None, lr_scheduler='constant', lr_warmup_steps=0, lr_scheduler_num_cycles=1, lr_scheduler_power=1, fused_backward_pass=False, dataset_config=None, min_snr_gamma=None, scale_v_pred_loss_like_noise_pred=False, v_pred_like_loss=None, debiased_estimation_loss=False, weighted_captions=False, no_metadata=False, save_model_as='safetensors', unet_lr=None, text_encoder_lr=None, network_weights=None, network_module=None, network_dim=None, network_alpha=1, network_dropout=None, network_args=None, network_train_unet_only=False, network_train_text_encoder_only=False, training_comment=None, dim_from_weights=False, scale_weight_norms=None, base_weights=None, base_weights_multiplier=None, no_half_vae=False, skip_until_initial_step=False, initial_epoch=None, initial_step=None)
2024-08-24 23:30:57 INFO     t5xxl_max_token_length: 512                               flux_train_network_comfy.py:109
                    INFO     Loading dataset config from [[datasets]]                             train_network.py:271
                             resolution = [ 512, 512,]
                             batch_size = 1
                             enable_bucket = false
                             bucket_no_upscale = false
                             [[datasets.subsets]]
                             image_dir = "../datasets/xiaozhuzhuv6notag"
                             class_tokens = "xzzc"
                             num_repeats = 1

                             [general]
                             shuffle_caption = false
                             caption_extension = ".txt"
                             keep_tokens_separator = "|||"
                             caption_dropout_rate = 0.0
                             color_aug = false
                             flip_aug = false

                    INFO     prepare images.                                                        train_util.py:1811
                    INFO     get image size from name of cache files                                train_util.py:1745
0it [00:00, ?it/s]
                    INFO     set image size from cache files: 0/0                                   train_util.py:1752
                    INFO     found directory ../datasets/xiaozhuzhuv6notag contains 0 image files   train_util.py:1754
                    WARNING  ignore subset with image_dir='../datasets/xiaozhuzhuv6notag': no       train_util.py:1830
                             images found / 画像が見つからないためサブセットを無視します
                    INFO     0 train images with repeating.                                         train_util.py:1852
                    INFO     0 reg images.                                                          train_util.py:1855
                    WARNING  no regularization images / 正則化画像が見つかりませんでした            train_util.py:1860
                    INFO     [Dataset 0]                                                            config_util.py:570
                               batch_size: 1
                               resolution: (512, 512)
                               enable_bucket: False
                               network_multiplier: 1.0

                    INFO     [Dataset 0]                                                            config_util.py:576
                    INFO     loading image sizes.                                                    train_util.py:876
0it [00:00, ?it/s]
                    INFO     prepare dataset                                                         train_util.py:884
                    ERROR    No data found. Please verify arguments (train_data_dir must be the   train_network.py:323
                             parent of folders with images) /
                             画像がありません。引数指定を確認してください（train_data_dirには画像
                             があるフォルダではなく、画像があるフォルダの親フォルダを指定する必要
                             があります）
                    ERROR    !!! Exception during processing !!! 'FluxNetworkTrainer' object has no   execution.py:386
                             attribute 'num_train_epochs'
                    ERROR    Traceback (most recent call last):                                       execution.py:387
                               File "E:\IMAGE\ComfyUI_MasterTask\ComfyUI\execution.py", line 317, in
                             execute
                                 output_data, output_ui, has_subgraph = get_output_data(obj,
                             input_data_all, execution_block_cb=execution_block_cb,
                             pre_execute_cb=pre_execute_cb)
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^
                               File "E:\IMAGE\ComfyUI_MasterTask\ComfyUI\execution.py", line 192, in
                             get_output_data
                                 return_values = _map_node_over_list(obj, input_data_all,
                             obj.FUNCTION, allow_interrupt=True,
                             execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^^^^^^^^^^^^^^^^^^
                               File "E:\IMAGE\ComfyUI_MasterTask\ComfyUI\execution.py", line 169, in
                             _map_node_over_list
                                 process_inputs(input_dict, i)
                               File "E:\IMAGE\ComfyUI_MasterTask\ComfyUI\execution.py", line 158, in
                             process_inputs
                                 results.append(getattr(obj, func)(**inputs))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "E:\IMAGE\ComfyUI_MasterTask\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\no
                             des.py", line 347, in init_training
                                 epochs_count = network_trainer.num_train_epochs
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             AttributeError: 'FluxNetworkTrainer' object has no attribute
                             'num_train_epochs'

                    INFO     Prompt executed in 0.80 seconds                                               main.py:134

**Comment by whmc76** [comment]
![image](https://github.com/user-attachments/assets/73c82ec4-2a38-404e-8f5a-b0576c35f753)
