### ISSUE TITLE
 FluxTrainLoop - text encoder - 'NoneType' object has no attribute 'to'

### ISSUE THREAD

**Issue by SPOOKEXE** [kijai/ComfyUI-FluxTrainer#102]
```2024-12-02T00:05:00.867360 - 2024-12-02 00:05:00 INFO     unet dtype: torch.float8_e4m3fn, device: cuda:0                       train_network.py:1061
2024-12-02T00:05:00.870357 -                     INFO     text_encoder [0] dtype: torch.float8_e4m3fn, device: cuda:0           train_network.py:1067
2024-12-02T00:05:00.873386 -                     INFO     text_encoder [1] dtype: torch.float16, device: cpu                    train_network.py:1067
2024-12-02T00:05:01.178265 - 
Epoch 1/9 - steps:   0%|                                                                      | 0/1000 [00:00<?, ?it/s]2024-12-02T00:05:01.303196 - 2024-12-02 00:05:01 ERROR    !!! Exception during processing !!! 'NoneType' object has no attribute     execution.py:392
                             'to'                                                                                       
2024-12-02T00:05:01.312193 -                     ERROR    Traceback (most recent call last):                                         execution.py:393
                               File "C:\Users\Administrator\Desktop\ComfyUI\execution.py", line 323, in                 
                             execute                                                                                    
                                 output_data, output_ui, has_subgraph = get_output_data(obj,                            
                             input_data_all, execution_block_cb=execution_block_cb,                                     
                             pre_execute_cb=pre_execute_cb)                                                             
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^                                                                                          
                               File "C:\Users\Administrator\Desktop\ComfyUI\execution.py", line 198, in                 
                             get_output_data                                                                            
                                 return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION,                 
                             allow_interrupt=True, execution_block_cb=execution_block_cb,                               
                             pre_execute_cb=pre_execute_cb)                                                             
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^^^^^^^^^                                                                         
                               File "C:\Users\Administrator\Desktop\ComfyUI\execution.py", line 169, in                 
                             _map_node_over_list                                                                        
                                 process_inputs(input_dict, i)                                                          
                               File "C:\Users\Administrator\Desktop\ComfyUI\execution.py", line 158, in                 
                             process_inputs                                                                             
                                 results.append(getattr(obj, func)(**inputs))                                           
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                            
                               File                                                                                     
                             "C:\Users\Administrator\Desktop\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\n                 
                             odes.py", line 837, in train                                                               
                                 steps_done = training_loop(                                                            
                                              ^^^^^^^^^^^^^^                                                            
                               File                                                                                     
                             "C:\Users\Administrator\Desktop\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\t                 
                             rain_network.py", line 1166, in training_loop                                              
                                 encoded_text_encoder_conds = [c.to(weight_dtype) for c in                              
                             encoded_text_encoder_conds]                                                                
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
                             ^^^^^^^^^^^^^^^                                                                            
                               File                                                                                     
                             "C:\Users\Administrator\Desktop\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\t                 
                             rain_network.py", line 1166, in <listcomp>                                                 
                                 encoded_text_encoder_conds = [c.to(weight_dtype) for c in                              
                             encoded_text_encoder_conds]                                                                
                                                               ^^^^                                                     
                             AttributeError: 'NoneType' object has no attribute 'to'                                    
                                                                                                                        
2024-12-02T00:05:01.320190 -                     INFO     Prompt executed in 119.99 seconds                                               main.py:139```

**Comment by SPOOKEXE** [comment]
For commit 688482c0b49da2d26d3c62753b3e541184feb962 (most recent as of this message)

**Comment by SPOOKEXE** [comment]
Transformer = flux1-dev.safetensors
Vae = ae.safetensors
clip_l = clip_l.safetensors
t5 = t5xxl_fp16.safetensors

**Comment by ymjkoo** [comment]
Is there any update on this? I'm encountering the same issue as well. As far as I'm lead to believe the LoRA won't be trained with captions in mind if 'train-text-encoder' is not enabled.

**Comment by SPOOKEXE** [comment]
No update, if you're still getting the error its not likely fixed

**Comment by SPOOKEXE** [comment]
Unlikely to be fixed
