### ISSUE TITLE
 TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by bananasss00** [kijai/ComfyUI-FluxTrainer#16]
I get this error right after generating the validation image, but the validation image is generated successfully:
```
2024-08-27 01:06:40 INFO     text_encoder is not needed for training. deleting to save memory.     train_network.py:1006
                    INFO     unet dtype: torch.float8_e4m3fn, device: cuda:0                       train_network.py:1023
Epoch 1/4 - steps:  25%|██████████▊                                | 182/728 [23:32<1:10:36,  7.76s/it, avr_loss=0.463]2024-08-27 01:30:13 INFO                                                                          flux_train_utils.py:44
                    INFO     generating sample images at step: 182                                flux_train_utils.py:45
                    INFO     prompt: girl                                                       flux_train_utils.py:168
                    INFO     height: 1024                                                        flux_train_utils.py:170
                    INFO     width: 1024                                                         flux_train_utils.py:171
                    INFO     sample_steps: 20                                                    flux_train_utils.py:172
                    INFO     scale: 3.0                                                          flux_train_utils.py:173
                    INFO     seed: 42                                                            flux_train_utils.py:176
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [02:36<00:00,  7.83s/it]
2024-08-27 01:32:53 ERROR    !!! Exception during processing !!! unsupported operand type(s) for +:     execution.py:386
                             'NoneType' and 'float'
                    ERROR    Traceback (most recent call last):                                         execution.py:387
                               File "V:\comfyu_py311\ComfyUI\execution.py", line 317, in execute
                                 output_data, output_ui, has_subgraph = get_output_data(obj,
                             input_data_all, execution_block_cb=execution_block_cb,
                             pre_execute_cb=pre_execute_cb)
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^
                               File "V:\comfyu_py311\ComfyUI\execution.py", line 192, in
                             get_output_data
                                 return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION,
                             allow_interrupt=True, execution_block_cb=execution_block_cb,
                             pre_execute_cb=pre_execute_cb)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^^^^^^^^^^^^^^
                               File "V:\comfyu_py311\ComfyUI\execution.py", line 169, in
                             _map_node_over_list
                                 process_inputs(input_dict, i)
                               File "V:\comfyu_py311\ComfyUI\execution.py", line 158, in process_inputs
                                 results.append(getattr(obj, func)(**inputs))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\nodes.py", line
                             834, in validate
                                 return (trainer, (0.5 * (image_tensors + 1.0)).cpu().float(),)
                                                          ~~~~~~~~~~~~~~^~~~~
                             TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

                    INFO     Prompt executed in 1703.73 seconds                                              main.py:134 
```
![image](https://github.com/user-attachments/assets/758a1b55-44dc-4ce8-bc82-0d78e1686301)

**Comment by kijai** [comment]
There was an error in the split_mode validation, it was never returning the results, that's fixed now.
