### ISSUE TITLE
'FluxNetworkTrainer' object has no attribute 'num_train_epochs'

### ISSUE THREAD

**Issue by Luckyjjjjjjj** [kijai/ComfyUI-FluxTrainer#19]
I keep getting the error 'FluxNetworkTrainer' object has no attribute 'num_train_epochs', but I can't find a place to fill in train_epochs

**Comment by kijai** [comment]
It's calculated automatically, I don't know why you'd get that error though, you are on latest version with latest example workflow?

**Comment by Orenji-Tangerine** [comment]
The default workflow max_train_steps is 10 maybe can try to change that to 3000 to accommodate with the value input of 750 x 4 nodes behind or you work out your combinations.

**Comment by Orenji-Tangerine** [comment]
Sorry, I dont know why mine is a 10 when I opened up, but I just check Kijai latest workflow, it is in fact 3000. My apologies.

**Comment by kijai** [comment]
> Sorry, I dont know why mine is a 10 when I opened up, but I just check Kijai latest workflow, it is in fact 3000. My apologies.

It was my mistake at one point, I was testing stuff and forgot to change it. Current workflow should have the 3000 indeed.

**Comment by Luckyjjjjjjj** [comment]
I used the default 3000 and 750 rounds 4 times each, and also tried 4000 and 100 rounds 4 times each, all of them reported errors, I don't know where I went wrong...

**Comment by kijai** [comment]
Something about the initial settings must be very wrong, make sure all the paths are pointing to right place, and if you want, you could copy the whole log up to the point it fails here so I can take a look.

**Comment by Luckyjjjjjjj** [comment]
is this one？

Error occurred when executing InitFluxLoRATraining:

'FluxNetworkTrainer' object has no attribute 'num_train_epochs'

File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
process_inputs(input_dict, i)
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
results.append(getattr(obj, func)(**inputs))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\nodes.py", line 398, in init_training
epochs_count = network_trainer.num_train_epochs

**Comment by kijai** [comment]
> is this one？
> 
> Error occurred when executing InitFluxLoRATraining:
> 
> 'FluxNetworkTrainer' object has no attribute 'num_train_epochs'
> 
> File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list process_inputs(input_dict, i) File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs results.append(getattr(obj, func)(**inputs)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\nodes.py", line 398, in init_training epochs_count = network_trainer.num_train_epochs

There's nothing before that? I mean the whole log before that point as well.

**Comment by Chzzll** [comment]
I have encountered the same problem. I hope I can give you a reference. Thank you：
INFO     [Dataset 0]                                                                                config_util.py:576
                    INFO     loading image sizes.                                                                        train_util.py:876
0it [00:00, ?it/s]                                                                                                                        
                    INFO     make buckets                                                                                train_util.py:882
                    INFO     number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）             train_util.py:928
                    INFO     mean ar error (without repeats): nan                                                        train_util.py:938
                    ERROR    No data found. Please verify arguments (train_data_dir must be the parent of folders     train_network.py:323
                             with images) /                                                                                               
                             画像がありません。引数指定を確認してください（train_data_dirには画像があるフォルダではな                     
                             く、画像があるフォルダの親フォルダを指定する必要があります）                                                 
                    ERROR    !!! Exception during processing !!! 'FluxNetworkTrainer' object has no attribute             execution.py:386
                             'num_train_epochs'                                                                                           
                    ERROR    Traceback (most recent call last):                                                           execution.py:387
                               File "E:\ComfyUI\execution.py", line 317, in execute                                                       
                                 output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all,                              
                             execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)                                        
                               File "E:\ComfyUI\execution.py", line 192, in get_output_data                                               
                                 return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION,                                   
                             allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)                  
                               File "E:\ComfyUI\execution.py", line 169, in _map_node_over_list                                           
                                 process_inputs(input_dict, i)                                                                            
                               File "E:\ComfyUI\execution.py", line 158, in process_inputs                                                
                                 results.append(getattr(obj, func)(**inputs))                                                             
                               File "E:\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\nodes.py", line 412, in init_training                    
                                 epochs_count = network_trainer.num_train_epochs                                                          
                             AttributeError: 'FluxNetworkTrainer' object has no attribute 'num_train_epochs'                              
                                                                                                                                          
                    INFO     Prompt executed in 1.73 seconds                                                                   main.py:134

**Comment by kijai** [comment]
> I have encountered the same problem. I hope I can give you a reference. Thank you：
> INFO     [Dataset 0]                                                                                config_util.py:576
>                     INFO     loading image sizes.                                                                        train_util.py:876
> 0it [00:00, ?it/s]                                                                                                                        
>                     INFO     make buckets                                                                                train_util.py:882
>                     INFO     number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）             train_util.py:928
>                     INFO     mean ar error (without repeats): nan                                                        train_util.py:938
>                     ERROR    No data found. Please verify arguments (train_data_dir must be the parent of folders     train_network.py:323
>                              with images) /                                                                                               
>                              画像がありません。引数指定を確認してください（train_data_dirには画像があるフォルダではな                     
>                              く、画像があるフォルダの親フォルダを指定する必要があります）                                                 
>                     ERROR    !!! Exception during processing !!! 'FluxNetworkTrainer' object has no attribute             execution.py:386
>                              'num_train_epochs'                                                                                           
>                     ERROR    Traceback (most recent call last):                                                           execution.py:387
>                                File "E:\ComfyUI\execution.py", line 317, in execute                                                       
>                                  output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all,                              
>                              execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)                                        
>                                File "E:\ComfyUI\execution.py", line 192, in get_output_data                                               
>                                  return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION,                                   
>                              allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)                  
>                                File "E:\ComfyUI\execution.py", line 169, in _map_node_over_list                                           
>                                  process_inputs(input_dict, i)                                                                            
>                                File "E:\ComfyUI\execution.py", line 158, in process_inputs                                                
>                                  results.append(getattr(obj, func)(**inputs))                                                             
>                                File "E:\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\nodes.py", line 412, in init_training                    
>                                  epochs_count = network_trainer.num_train_epochs                                                          
>                              AttributeError: 'FluxNetworkTrainer' object has no attribute 'num_train_epochs'                              
>                                                                                                                                           
>                     INFO     Prompt executed in 1.73 seconds                                                                   main.py:134

The dataset directory is not set correctly and it can't find the images to train with.

**Comment by SudaBad** [comment]
make sure to get rid of the " " when you copy path guys 🤦

**Comment by TristanMorelle** [comment]
had this error when my image path was outdated, so yeah check those

**Comment by microvswind** [comment]
got this error too
initfluxloratraining
"fluxnetworktrainer" boject has no attribute "num_train_epochs"

**Comment by Herbys68** [comment]
Invalid paths for the images (e.g. surrounded by quotes) will cause this error. Not sure why it isn't being fixed in the code with a more specific error, it's been there for a while and it confuses lots of people given the entirely misleading error message.

**Comment by Crueltyan** [comment]
报错原因大部分出在路径上，过期、带引号、换行，均会出现上述错误

**Comment by abomonov** [comment]
What kind of idiot made that shit script? Can't run links on linux because of this bug.

**Comment by panyanhui47** [comment]
请问这个问题解决了吗

**Comment by JDSYYL** [comment]
> 请问这个问题解决了吗

解决了，是图片路径问题。

**Comment by JDSYYL** [comment]
> 请问这个问题解决了吗

解决了，是图片路径问题，报错提示有误，训练集路径必须是训练素材所在的文件夹路径

**Comment by henrybastos** [comment]
Hello! I was having the same problem, fixed it by using the same path in both nodes:

<img width="260" height="771" alt="Image" src="https://github.com/user-attachments/assets/192646d8-124c-492f-bff8-1b8d6139fcb7" />

Also, I had to change the Save Images node, I had an old one that wasn't working. Hope this helps

**Comment by CG1995** [comment]
I want to talk about how I solved it, because when I asked GPT, it gave me a bunch of suggestions, none of which were useful. Until I read all the comment areas and changed the address of the dataset, the entire workflow ran smoothly. I think the root cause of the problem was that the log reported a log that did not match the real error.

**Comment by InfernoChicken** [comment]
i also came across this error today and could not get it to run until I tried to ditch the relative file path and just put in the total file path. so instead trying to find the correct syntax I just went ahead and put in: "C:\AI\ComfyUI\datasets\(your_project)" and it worked lmao

**Comment by Kozatiju** [comment]
> i also came across this error today and could not get it to run until I tried to ditch the relative file path and just put in the total file path. so instead trying to find the correct syntax I just went ahead and put in: "C:\AI\ComfyUI\datasets(your_project)" and it worked lmao

THIS !!!!

**Comment by OrangeIcecubes** [comment]
The error can also appear if there's a subfolder in your image-folder.
