### ISSUE TITLE
No module named 'networks.lora_flux'

### ISSUE THREAD

**Issue by Chzzll** [kijai/ComfyUI-FluxTrainer#27]
Error occurred when executing InitFluxLoRATraining:

No module named 'networks.lora_flux'; 'networks' is not a package

File "E:\ComfyUI\execution.py", line 317, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "E:\ComfyUI\execution.py", line 192, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "E:\ComfyUI\execution.py", line 169, in _map_node_over_list
process_inputs(input_dict, i)
File "E:\ComfyUI\execution.py", line 158, in process_inputs
results.append(getattr(obj, func)(**inputs))
File "E:\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\nodes.py", line 430, in init_training
training_loop = network_trainer.init_train(args)
File "E:\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\train_network.py", line 361, in init_train
for i, weight_path in enumerate(args.base_weights):
File "C:\Users\22939\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1050, in _gcd_import
File "", line 1027, in _find_and_load
File "", line 1001, in _find_and_load_unlocked

**Comment by codingcn** [comment]
same issues


```
 ERROR    !!! Exception during processing !!! No module named 'networks.lora_flux'   execution.py:386
                    ERROR    Traceback (most recent call last):                                         execution.py:387
                               File "E:\ComfyUI\execution.py", line 317, in execute
                                 output_data, output_ui, has_subgraph = get_output_data(obj,
                             input_data_all, execution_block_cb=execution_block_cb,
                             pre_execute_cb=pre_execute_cb)
                               File "E:\ComfyUI\execution.py", line 192, in get_output_data
                                 return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION,
                             allow_interrupt=True, execution_block_cb=execution_block_cb,
                             pre_execute_cb=pre_execute_cb)
                               File "E:\ComfyUI\execution.py", line 169, in _map_node_over_list
                                 process_inputs(input_dict, i)
                               File "E:\ComfyUI\execution.py", line 158, in process_inputs
                                 results.append(getattr(obj, func)(**inputs))
                               File "E:\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\nodes.py", line 430,
                             in init_training
                                 training_loop = network_trainer.init_train(args)
                               File "E:\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\train_network.py",
                             line 357, in init_train
                                 network_module = importlib.import_module(args.network_module)
                               File
                             "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\importlib\__in
                             it__.py", line 126, in import_module
                                 return _bootstrap._gcd_import(name[level:], package, level)
                               File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
                               File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
                               File "<frozen importlib._bootstrap>", line 1004, in
                             _find_and_load_unlocked
                             ModuleNotFoundError: No module named 'networks.lora_flux'
```

**Comment by kijai** [comment]
Do you possible have some other custom node that uses kohya installed? There's probably some other package with module named "networks" installed and it tries to load that instead.

**Comment by codingcn** [comment]
> Reference

Your guess was right, I double-checked all the extensions I installed, and when I removed this extension, FluxTrainer worked fine

https://github.com/AIFSH/ComfyUI-3d-photo-inpainting

**Comment by kijai** [comment]
Changed that to relative import which should take care of such conflicts.
