### ISSUE TITLE
adafactor scheduler error IndexError: list index out of range

### ISSUE THREAD

**Issue by whmc76** [kijai/ComfyUI-FluxTrainer#30]
ERROR    !!! Exception during processing !!! list index out of range                execution.py:386
                    ERROR    Traceback (most recent call last):                                         execution.py:387
                               File "E:\IMAGE\ComfyUI_Training\ComfyUI\execution.py", line 317, in
                             execute
                                 output_data, output_ui, has_subgraph = get_output_data(obj,
                             input_data_all, execution_block_cb=execution_block_cb,
                             pre_execute_cb=pre_execute_cb)
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^
                               File "E:\IMAGE\ComfyUI_Training\ComfyUI\execution.py", line 192, in
                             get_output_data
                                 return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION,
                             allow_interrupt=True, execution_block_cb=execution_block_cb,
                             pre_execute_cb=pre_execute_cb)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^^^^^^^^^^^^^^
                               File "E:\IMAGE\ComfyUI_Training\ComfyUI\execution.py", line 169, in
                             _map_node_over_list
                                 process_inputs(input_dict, i)
                               File "E:\IMAGE\ComfyUI_Training\ComfyUI\execution.py", line 158, in
                             process_inputs
                                 results.append(getattr(obj, func)(**inputs))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "E:\IMAGE\ComfyUI_Training\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\nodes.
                             py", line 430, in init_training
                                 training_loop = network_trainer.init_train(args)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "E:\IMAGE\ComfyUI_Training\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\train_
                             network.py", line 517, in init_train
                                 lr_scheduler = train_util.get_scheduler_fix(args, optimizer,
                             accelerator.num_processes)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^^^^^^^^^^^^^
                               File
                             "E:\IMAGE\ComfyUI_Training\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\librar
                             y\train_util.py", line 4633, in get_scheduler_fix
                                 initial_lr = float(name.split(":")[1])
                                                    ~~~~~~~~~~~~~~~^^^
                             IndexError: list index out of range

**Comment by whmc76** [comment]
![image](https://github.com/user-attachments/assets/56bd44ba-ffa6-4809-9fdb-0a036256c93a)

**Comment by whmc76** [comment]
i can run with constant, but adafactor will failed

**Comment by BrokenEnigma** [comment]
I’m having the same issue with the adafactor and adamW8bit, get the index error.

Have you noticed a difference with constant?

if I run without the optimiser, it works fine.
