### ISSUE TITLE
[Feature Request] Avoid Duplication of TrainLoop and TrainValidate Nodes

### ISSUE THREAD

**Issue by m0rphism** [kijai/ComfyUI-FluxTrainer#45]
Currently, each time the user wants to save the current model and create validation images, requires creating another copy of the "Flux Train Loop", "Flux Train Validate", and "Flux Train Save LoRA" nodes.

This doesn't scale well for large training sessions where one wants to save and validate often.

On larger datasets I often train for over 50000 steps and save and validate every 500 steps, which would require me to create 100 copies of those nodes.

Even if a large amount of steps is not always necessary, this workflow can be nice for exploratory trainings, where one simply continues training indefinitely (using constant learning rate). This way one can just let the training run in the background and every now and then check the validation images to see if sufficiently many concepts have been captured by the LoRA.

It would be nice if it would be possible to create those nodes only once, and have the `steps` parameter of the "Flux Train Loop" node mean "every n steps" instead of "after n steps".

Unfortunately, I'm not sure if it would then be possible to still use ComfyUI's computation graph, because the "Flux Train Validate" node would need to produce multiple outputs over time within one session created by clicking the "Queue prompt" button.

It might be possible by not using the "Preview Image" node, but instead using custom frontend display logic for the "Flux Train Validate" node, e.g. that the image is displayed as part of the "Flux Train Validate" node and the "Flux Train Validate" node can control itself when to update it, similar like the original KSampler node updates its preview images within one session.

Alternatively, one could provide a specialized "Flux Train Loop" node which does not use comfyui for displaying the results but simply writes the LoRA and validation images into a directory after each N training steps without using the ComfyUI computation graph logic. This way the user could then use a regular file browser and image viewer to inspect the current training progress.

**Comment by kijai** [comment]
Would love to do all this, but like you said it's mostly UX issue... no problem at all to do if we forget about showing the validation results of course. With the new comfy features that came with the execution order reversion would probably allow accumulating validation results to a batch or something though.

**Comment by SencneS** [comment]
> On larger datasets I often train for over 50000 steps and save and validate every 500 steps, which would require me to create 100 copies of those nodes.

I did what you described... While I was doing art style training I basically ended up with a LoRA that had 400,000 steps of training. Because the dataset was largish I guess. 80 images, 50 steps per loop, over 100 loops, Comes out to 400,000.
There was so little difference between so many of the saves I have now changed it to 125 steps per loop and 20 loops.
So that same 80 image set is 200,000 steps of training. Even at that rate, it still has little difference between the saves.
Like there is some BIG jumps all of a sudden, but nothing that appears to overtrain the LoRA.

I plan on using the 100 epoch steps for a big one, 200 images, 50 steps, 100 epochs when I go on a trip, which will be 1 million step LoRA to see if Flux training this way can actually break... because even my 400K steps one didn't produce abominations at all.

**Comment by kijai** [comment]
I think I actually made a node for this... but got so busy with other things that I never tested it, it won't show anything in comfy but should write the files normally:

![image](https://github.com/user-attachments/assets/c1276911-98cf-4b98-bace-7f9db24fbf02)

**Comment by SencneS** [comment]
> I think I actually made a node for this... but got so busy with other things that I never tested it, it won't show anything in comfy but should write the files normally:
> 
I'll give a little shot, let you know what it did, give a few days.

**Comment by Tr1dae** [comment]
Have you managed to get any success using that? I'm trying to set up a clean SDXL training file and I encounter 
'SdxlNetworkTrainer' object has no attribute 'sample_prompts_te_outputs' from the 'FluxTrainAndValidateLoop'

`2025-03-08 21:25:15 INFO     unet dtype: torch.bfloat16, device: cuda:0                                                                train_network.py:1124
                    INFO     text_encoder [0] dtype: torch.float32, device: cpu                                                        train_network.py:1130
                    INFO     text_encoder [1] dtype: torch.float32, device: cpu                                                        train_network.py:1130
Epoch 3/125 - steps:   2%|█▌                                                                             | 10/500 [00:29<23:47,  2.91s/it, avr_loss=0.0682]2025-03-08 21:25:44 ERROR    !!! Exception during processing !!! 'SdxlNetworkTrainer' object has no attribute 'sample_prompts_te_outputs'   execution.py:396
                    ERROR    Traceback (most recent call last):                                                                             execution.py:397
                               File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 327, in execute
                                 output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all,
                             execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 202, in get_output_data
                                 return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True,
                             execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
                                 process_inputs(input_dict, i)
                               File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
                                 results.append(getattr(obj, func)(**inputs))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File "X:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-fluxtrainer\nodes.py", line 961, in train
                                 self.validate(network_trainer, validation_settings)
                               File "X:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-fluxtrainer\nodes.py", line 986, in validate
                                 network_trainer.sample_prompts_te_outputs,
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             AttributeError: 'SdxlNetworkTrainer' object has no attribute 'sample_prompts_te_outputs'
`

I'm using the example SDXL workflow to test and pretty much just plugged the connections directly as they were in the example. Is this because the Loop node is specific to FLux or are they universal? I can't seem to find a SDXL variant

![Image](https://github.com/user-attachments/assets/188e0cc8-4d8f-4a7b-9632-5dd134bd1f73)
