### ISSUE TITLE
ERROR on start of training.  AttributeError: 'LoRANetwork' object has no attribute 'prepare_optimizer_params'

### ISSUE THREAD

**Issue by Maelstrom2014** [kijai/ComfyUI-FluxTrainer#55]
Here the problem:
                    INFO     create LoRA for Text Encoder 1:                                                            lora_flux.py:589
2024-09-11 23:19:45 INFO     create LoRA for Text Encoder 1: 72 modules.                                                lora_flux.py:592
                    INFO     create LoRA for FLUX single blocks: 2 modules.                                             lora_flux.py:606
                    INFO     enable LoRA for U-Net: 2 modules                                                           lora_flux.py:755
2024-09-11 23:19:45.276302 FLUX: Gradient checkpointing enabled.
2024-09-11 23:19:45.277302 prepare optimizer, data loader etc.
                    ERROR    !!! Exception during processing !!! 'LoRANetwork' object has no attribute                  execution.py:386
                             'prepare_optimizer_params'
                    ERROR    Traceback (most recent call last):                                                         execution.py:387
                               File "C:\ai\comfyui\ComfyUI\execution.py", line 317, in execute
                                 output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all,
                             execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File "C:\ai\comfyui\ComfyUI\execution.py", line 192, in get_output_data
                                 return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION,
                             allow_interrupt=True, execution_block_cb=execution_block_cb,
                             pre_execute_cb=pre_execute_cb)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File "C:\ai\comfyui\ComfyUI\execution.py", line 169, in _map_node_over_list
                                 process_inputs(input_dict, i)
                               File "C:\ai\comfyui\ComfyUI\execution.py", line 158, in process_inputs
                                 results.append(getattr(obj, func)(**inputs))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File "C:\ai\comfyui\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\nodes.py", line 472, in
                             init_training
                               File "C:\ai\comfyui\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\train_network.py", line
                             477, in init_train
                                 if support_multiple_lrs:
                                               ^^^^^^^^^^^
                               File "C:\ai\comfyui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line
                             1729, in __getattr__
                                 raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
                             AttributeError: 'LoRANetwork' object has no attribute 'prepare_optimizer_params'

2024-09-11 23:19:45.312300 #107 [InitFluxLoRATraining]: 307.67s
                    INFO     Prompt executed in 308.18 seconds                                                               main.py:138

**Comment by Maelstrom2014** [comment]
fixed with update "git pull" and restart
