### ISSUE TITLE
extract flux lora report "File does not contain tensor double_blocks.0.img_attn.proj.weight" error

### ISSUE THREAD

**Issue by deepfree2023** [kijai/ComfyUI-FluxTrainer#65]
![image](https://github.com/user-attachments/assets/2a69219b-e70b-4fa5-ba78-a1396203f1da)

Traceback (most recent call last):
  File "K:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "K:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\nodes.py", line 1542, in extract
    outpath = svd(
              ^^^^
  File "K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\flux_extract_lora.py", line 87, in svd
    value_t = ft.get_tensor(key)
              ^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: File does not contain tensor double_blocks.0.img_attn.proj.weight

**Comment by kijai** [comment]
Where is that finetuned model from? I think the underlaying kohya script only supports LoRAs trained with kohya.

**Comment by deepfree2023** [comment]
From civitai, it is possible to make this node universal to support extracting other LORAs?

**Comment by kijai** [comment]
Everything is possible, but for this I wouldn't know how.... Comfy has added more generic LoRa extract node into comfyui though, maybe try that.

**Comment by bananasss00** [comment]
> Everything is possible, but for this I wouldn't know how.... Comfy has added more generic LoRa extract node into comfyui though, maybe try that.

I encountered a situation with such a model. The issue turned out to be simple: the model had a prefix "model.diffusion_model.", while the original model did not have this prefix. As a result, the LoRA extractor could not match the keys of the two models.

This can be resolved by, for example, modifying the code as follows:
```py
with open_fn(model_tuned) as f_tuned:
    for key in tqdm(keys):
        key2 = key if key in f_tuned.keys() else 'model.diffusion_model.' + key
        
        if key2 not in f_tuned.keys():
            print(f'{key} not found')
            continue
            
        # get tensors and calculate difference
        value_o = f_org.get_tensor(key)
        value_t = f_tuned.get_tensor(key2)

```

**Comment by retronomi** [comment]
> > Everything is possible, but for this I wouldn't know how.... Comfy has added more generic LoRa extract node into comfyui though, maybe try that.
> 
> I encountered a situation with such a model. The issue turned out to be simple: the model had a prefix "model.diffusion_model.", while the original model did not have this prefix. As a result, the LoRA extractor could not match the keys of the two models.
> 
> This can be resolved by, for example, modifying the code as follows:
> 
> ```python
> with open_fn(model_tuned) as f_tuned:
>     for key in tqdm(keys):
>         key2 = key if key in f_tuned.keys() else 'model.diffusion_model.' + key
>         
>         if key2 not in f_tuned.keys():
>             print(f'{key} not found')
>             continue
>             
>         # get tensors and calculate difference
>         value_o = f_org.get_tensor(key)
>         value_t = f_tuned.get_tensor(key2)
> ```

Was having this issue in kohya_ss and this worked for me, thanks!

**Comment by ShoponSKP** [comment]
> > > Everything is possible, but for this I wouldn't know how.... Comfy has added more generic LoRa extract node into comfyui though, maybe try that.
> > 
> > 
> > I encountered a situation with such a model. The issue turned out to be simple: the model had a prefix "model.diffusion_model.", while the original model did not have this prefix. As a result, the LoRA extractor could not match the keys of the two models.
> > This can be resolved by, for example, modifying the code as follows:
> > ```python
> > with open_fn(model_tuned) as f_tuned:
> >     for key in tqdm(keys):
> >         key2 = key if key in f_tuned.keys() else 'model.diffusion_model.' + key
> >         
> >         if key2 not in f_tuned.keys():
> >             print(f'{key} not found')
> >             continue
> >             
> >         # get tensors and calculate difference
> >         value_o = f_org.get_tensor(key)
> >         value_t = f_tuned.get_tensor(key2)
> > ```
> 
> Was having this issue in kohya_ss and this worked for me, thanks!


I am having this issue in kohya ss! But I am unable to modify the flux_extract_lora_gui.py with this fix code !! I tryed some times but somply it didnt work or the kohya ss it self is not starting.. can you please guide me ?

**Comment by ShoponSKP** [comment]
> > Everything is possible, but for this I wouldn't know how.... Comfy has added more generic LoRa extract node into comfyui though, maybe try that.
> 
> I encountered a situation with such a model. The issue turned out to be simple: the model had a prefix "model.diffusion_model.", while the original model did not have this prefix. As a result, the LoRA extractor could not match the keys of the two models.
> 
> This can be resolved by, for example, modifying the code as follows:
> 
> ```python
> with open_fn(model_tuned) as f_tuned:
>     for key in tqdm(keys):
>         key2 = key if key in f_tuned.keys() else 'model.diffusion_model.' + key
>         
>         if key2 not in f_tuned.keys():
>             print(f'{key} not found')
>             continue
>             
>         # get tensors and calculate difference
>         value_o = f_org.get_tensor(key)
>         value_t = f_tuned.get_tensor(key2)
> ```
I am having this issue in kohya ss! But I am unable to modify the flux_extract_lora_gui.py with this fix code !! I tryed some times but somply it didnt work or the kohya ss it self is not starting.. can you please guide me ?

**Comment by deeplearner5** [comment]
Sorry if it's a bit of a necro, but in reply to the previous post re: the fix on kohya, the amendment on flux_extract_lora.py needs to replace a couple of lines of the existing code:

```
        with open_fn(model_tuned) as f_tuned:
            for key in tqdm(keys):
                # Original code:
                # value_o = f_org.get_tensor(key)
                # value_t = f_tuned.get_tensor(key)

                # New logic to check for key existence in f_tuned
                key2 = key if key in f_tuned.keys() else 'model.diffusion_model.' + key
                
                if key2 not in f_tuned.keys():
                    print(f'{key} not found in model_tuned')
                    continue

                # Get tensors and calculate difference
                value_o = f_org.get_tensor(key)
                value_t = f_tuned.get_tensor(key2)
```
