### ISSUE TITLE
InitFluxLoRATraining: "Cannot copy out of meta tensor; no data!"

### ISSUE THREAD

**Issue by dkhold** [kijai/ComfyUI-FluxTrainer#80]
Hello,

Thanks for providing these nodes! I've used the reference `workflow.json` from the repository.

I successfully preprocessed the images (steps 1-4) but when actually starting the training, I get the error below.
I made sure to select the original `ae.safetensors` and `flux-dev.safetensors`. I also tried with `flux-dev-fp8`, same error.
I tried with and without highvram, with and without split_mode, with and without base_fp8.

For some reason, moving the `text_encoders` to the GPU is failing as can be seen below.

Problematic lines: [here](https://github.com/kijai/ComfyUI-FluxTrainer/blob/main/flux_train_network_comfy.py#L220) or [here](https://github.com/kijai/ComfyUI-FluxTrainer/blob/main/flux_train_network_comfy.py#L288).

```
Error occurred when executing InitFluxLoRATraining:

Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.

File "/stable-diffusion/execution.py", line 316, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "/stable-diffusion/execution.py", line 191, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "/stable-diffusion/execution.py", line 168, in _map_node_over_list
process_inputs(input_dict, i)
File "/stable-diffusion/execution.py", line 157, in process_inputs
results.append(getattr(obj, func)(**inputs))
File "/data/config/comfy/custom_nodes/ComfyUI-FluxTrainer/nodes.py", line 523, in init_training
training_loop = network_trainer.init_train(args)
File "/data/config/comfy/custom_nodes/ComfyUI-FluxTrainer/train_network.py", line 406, in init_train
self.cache_text_encoder_outputs_if_needed(args, accelerator, unet, vae, text_encoders, train_dataset_group, weight_dtype)
File "/data/config/comfy/custom_nodes/ComfyUI-FluxTrainer/flux_train_network_comfy.py", line 220, in cache_text_encoder_outputs_if_needed
text_encoders[0].to(accelerator.device, dtype=weight_dtype) # always not fp8
File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2905, in to
return super().to(*args, **kwargs)
(snip torch internal calls)
```

![image](https://github.com/user-attachments/assets/d4c67fbe-5074-4627-9374-6ebb5815a6f3)

**Comment by kijai** [comment]
Meta tensor error like that means it's trying to move empty model, so if it's when it's trying to move text encoder, then there's something wrong with the text encoder files.

**Comment by ZGpork** [comment]
Have the same problem, I set this all up just for nothing now ;-(

**Comment by annedaphne** [comment]
> 遇到同样的问题，我现在白白设置了这一切 ;-（
> 
> 编辑：啊，它似乎不适用于我想尝试的去静止模型

same problem

**Comment by annedaphne** [comment]
> Have the same problem, I set this all up just for nothing now ;-(
> 
> edit: ah, it just does not seem to work with the de-destilled model which I wanted to try

same problem

**Comment by EnragedAntelope** [comment]
I am not using a de-distilled version. I have python 3.11.9, torch 2.4.1+cu124 .
I am receiving the same error. Any fix?

```
import network module: .networks.lora_flux
                    ERROR    !!! Exception during processing !!! Cannot copy out of meta tensor; no data! Please use execution.py:392
                             torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta
                             to a different device.
                    ERROR    Traceback (most recent call last):                                                      execution.py:393
                               File "D:\ComfyUI\execution.py", line 323, in execute
                                 output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all,
                             execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File "D:\ComfyUI\execution.py", line 198, in get_output_data
                                 return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION,
                             allow_interrupt=True, execution_block_cb=execution_block_cb,
                             pre_execute_cb=pre_execute_cb)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File "D:\ComfyUI\execution.py", line 169, in _map_node_over_list
                                 process_inputs(input_dict, i)
                               File "D:\ComfyUI\execution.py", line 158, in process_inputs
                                 results.append(getattr(obj, func)(**inputs))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File "D:\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\nodes.py", line 523, in
                             init_training
                                 training_loop = network_trainer.init_train(args)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File "D:\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\train_network.py", line 390, in
                             init_train
                                 vae.to(accelerator.device, dtype=vae_dtype)
                               File "D:\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1174, in to
                                 return self._apply(convert)
                                        ^^^^^^^^^^^^^^^^^^^^
                               File "D:\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 780, in
                             _apply
                                 module._apply(fn)
                               File "D:\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 780, in
                             _apply
                                 module._apply(fn)
                               File "D:\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 780, in
                             _apply
                                 module._apply(fn)
                               [Previous line repeated 3 more times]
                               File "D:\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 805, in
                             _apply
                                 param_applied = fn(param)
                                                 ^^^^^^^^^
                               File "D:\ComfyUI\venv\Lib\site-packages\torch\nn\modules\module.py", line 1167, in
                             convert
                                 raise NotImplementedError(
                             NotImplementedError: Cannot copy out of meta tensor; no data! Please use
                             torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta
                             to a different device.

end_vram - start_vram: 8234228418 - 1732385986 = 6501842432
#107 [InitFluxLoRATraining]: 10.85s - vram 6501842432b
                    INFO     Prompt executed in 10.89 seconds                                                             main.py:138
```

**Comment by fotoyang** [comment]
Had the same issue until I noticed author's README:

For LoRA training the models need to be the normal fp8 or fp16 versions, also make sure the VAE is the non-diffusers version:
https://huggingface.co/black-forest-labs/FLUX.1-dev/blob/main/ae.safetensors

Switched to the full size ae.safetensors (previously had a 159MB version) and everything worked!!!

**Comment by AlonFrd-AI** [comment]
was that fixed? I am having the same issue, already use fp16 VAE but still getting errors

**Comment by zimotgio-crypto** [comment]
I have still the same problem, is it a problem because of rtx5090?

**Comment by superheroinefans-spec** [comment]
I am getting the same error: "InitFluxLoRATraining
Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device."
Is there a solution? I am using the following model setup from a tutorial for LORA Training.

<img width="1131" height="782" alt="Image" src="https://github.com/user-attachments/assets/a7594564-e83a-4d7e-8a49-a9d020f6eae5" />

**Comment by bin-lian** [comment]
Can I resolve this issue?

**Comment by superheroinefans-spec** [comment]
I hope you can. It's very frustrating not to be able to use thuis function.

**Comment by kijai** [comment]
Make sure to select all the models yourself, the workflow may point to files that don't exist or are in incompatible format. If that doesn't help try some other VAE, I seem to recall kohya didn't support some VAE formats.

**Comment by wcmille** [comment]
When trying this model: https://huggingface.co/lllyasviel/flux1_dev/tree/main
I got the error message that others are getting.

When I replaced it with Kreamania, the error went away, though it didn't work with Kreamania.

Both models are in my diffusion models folder. The corresponding model was selected in Init Flux Lora Training in both cases.

I am wondering if the Illyasviel model might be the one people are getting because of this video:
https://www.bing.com/videos/riverview/relatedvideo?q=Flux+Lora+Training&&mid=F9929925E15A2EA23859F9929925E15A2EA23859&FORM=VAMGZC
See 7:08

But I think this is a checkpoint file, not a diffusion model. Could that be the problem?

**Comment by kijai** [comment]
> When trying this model: https://huggingface.co/lllyasviel/flux1_dev/tree/main I got the error message that others are getting.
> 
> When I replaced it with Kreamania, the error went away, though it didn't work with Kreamania.
> 
> Both models are in my diffusion models folder. The corresponding model was selected in Init Flux Lora Training in both cases.
> 
> I am wondering if the Illyasviel model might be the one people are getting because of this video: https://www.bing.com/videos/riverview/relatedvideo?q=Flux+Lora+Training&&mid=F9929925E15A2EA23859F9929925E15A2EA23859&FORM=VAMGZC See 7:08
> 
> But I think this is a checkpoint file, not a diffusion model. Could that be the problem?

Yes that is a file that includes other stuff as well, probably not supported by the kohya code.

**Comment by joed74** [comment]
I got this error too with `flux1-dev-fp8` and `flux1-krea-dev_fp8_scaled`

I changed Illyasviel model to [flux1-krea-dev.safetensors](https://huggingface.co/black-forest-labs/FLUX.1-Krea-dev/blob/main/flux1-krea-dev.safetensors) with [flux-vae-bf16.safetensors](https://huggingface.co/Kijai/flux-fp8/blob/main/flux-vae-bf16.safetensors), [t5xxl_fp16.safetensors](https://huggingface.co/Comfy-Org/stable-diffusion-3.5-fp8/blob/main/text_encoders/t5xxl_fp16.safetensors) and [clip_l.safetensors](https://huggingface.co/calcuis/sd3.5-large-gguf/blob/main/clip_l.safetensors)

<img width="634" height="234" alt="Image" src="https://github.com/user-attachments/assets/5c583114-0f7a-4fcc-aaee-94ffd8b832e3" />

After that change the training started - but i don't know if its working ok.. it is still working...

I use actual ComfyUI git-Version with AMD RX7900XTX 24GB and pytorch version 2.9.0+rocmsdk20251116 with ROCm version 7.1 on windows. 

For bitsandbytes on windows i had to copy this self compiled file into `site-packages\bitsandbytes`

[libbitsandbytes_rocm71.zip](https://github.com/user-attachments/files/24239831/libbitsandbytes_rocm71.zip)
